name: Deploy Backend
on:
  push:
    branches: [ dev ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH and Update Backend
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/noteTAking-BE
            git pull origin dev
            npm install --legacy-peer-deps
            npm run build
            # Restarts the specific PM2 process for the API
            pm2 restart ecosystem.config.js
            pm2 save